# Generated by Django 4.2.2 on 2023-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=8)),
                ('pin', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('lecturer', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
