# Generated by Django 4.2.2 on 2023-07-13 12:37

from django.db import migrations, models
import qrmark_backend.utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0009_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(qrmark_backend.utils.enums.Gender['MALE'], 'Mr'), (qrmark_backend.utils.enums.Gender['FEMALE'], 'Mrs')], max_length=10, null=True),
        ),
    ]
