# Generated by Django 4.2.2 on 2023-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('SEMESTER_1', 'SEMESTER_1'), ('SEMESTER_2', 'SEMESTER_2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('100', 'L100'), ('200', 'L200'), ('300', 'L300'), ('400', 'L400'), ('500', 'L500'), ('600', 'L600')], max_length=10, null=True),
        ),
    ]
