# Generated by Django 4.2.2 on 2023-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0015_lecturer_office_lecturer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
