# Generated by Django 4.2.2 on 2023-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0004_user_is_lecturer_user_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
    ]
