# Generated by Django 4.2.2 on 2023-07-13 12:39

from django.db import migrations, models
import qrmark_backend.utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0010_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(qrmark_backend.utils.enums.Gender['MALE'], 'MALE'), (qrmark_backend.utils.enums.Gender['FEMALE'], 'FEMALE'), (qrmark_backend.utils.enums.Gender['MR'], 'MR'), (qrmark_backend.utils.enums.Gender['MRS'], 'MRS')], max_length=10, null=True),
        ),
    ]
