# Generated by Django 4.2.2 on 2023-07-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0014_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
