# Generated by Django 4.2.2 on 2023-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0016_rename_course_course_title_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
