# Generated by Django 4.2.2 on 2023-08-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0018_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
