# Generated by Django 4.2.2 on 2023-08-27 20:49

from django.db import migrations, models
import django.db.models.deletion
import qrmark_database.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0019_qrcode_qr_code_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrmark_database.student'),
        ),
        migrations.CreateModel(
            name='UniqueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=qrmark_database.models.UniqueCode.generate_code, max_length=5)),
                ('valid_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrmark_database.course')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='qrmark_database.uniquecode'),
        ),
    ]
