# Generated by Django 4.2.2 on 2023-08-28 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0022_remove_uniquecode_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
