# Generated by Django 4.2.2 on 2023-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0023_course_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquecode',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
