# Generated by Django 4.2.2 on 2023-08-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmark_database', '0024_uniquecode_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'student__courses_enrolled__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='qrmark_database.student'),
        ),
    ]
